export const publicNewsUrl = 'https://newsapi.org/v2/everything?sortBy=popularity&apiKey=ef22b38c31ba4ed38c6d743b6eb163ba&language=ru&pageSize=100'
export const url = 'https://api.news-discoverer.ml/'
export const signin = 'https://api.news-discoverer.ml/signin'
export const signup = 'https://api.news-discoverer.ml/signup'
export const getInfoAboutMe = 'https://api.news-discoverer.ml/users/me'
export const articles = 'https://api.news-discoverer.ml/articles'
export const logout = 'https://api.news-discoverer.ml/logout'
